version: 2
updates:
  # Bi-weekly updates - All dependencies (Monday and Wednesday)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 9 * * 1,3" # Monday and Wednesday at 09:00 UTC
      timezone: "UTC"
    labels:
      - "dependencies"
      - "dependabot"
      - "bi-weekly-update"
    reviewers:
      - "llevintza"
    assignees:
      - "llevintza"
    open-pull-requests-limit: 25 # Total limit for both days
    commit-message:
      prefix: "deps: "
      include: "scope"

    # Strategic ecosystem grouping for all dependencies
    groups:
      # AWS ecosystem (all AWS-related packages)
      aws-ecosystem:
        patterns:
          - "@aws-sdk/*"
          - "aws-*"
        update-types:
          - "minor"
          - "patch"
          - "major" # AWS SDK major versions for coordinated updates

      # Fastify ecosystem (core framework and plugins)
      fastify-ecosystem:
        patterns:
          - "fastify"
          - "@fastify/*"
          - "fastify-plugin"
        update-types:
          - "minor"
          - "patch"
          - "major" # Include major versions for coordinated ecosystem updates

      # Production logging and utilities
      production-utilities:
        patterns:
          - "winston"
          - "winston-*"
          - "ajv"
        update-types:
          - "minor"
          - "patch"

      # TypeScript ecosystem (language and type definitions)
      typescript-ecosystem:
        patterns:
          - "typescript"
          - "@types/*"
          - "ts-*"
        update-types:
          - "minor"
          - "patch"
          - "major" # TypeScript major versions need coordinated updates

      # Linting and formatting tools (code quality)
      linting-and-formatting:
        patterns:
          - "eslint*"
          - "@typescript-eslint/*"
          - "prettier"
          - "@eslint/*"
          - "eslint-*"
        update-types:
          - "minor"
          - "patch"
          - "major" # Linting tools can have breaking config changes

      # Testing ecosystem (Jest and testing utilities)
      testing-ecosystem:
        patterns:
          - "jest"
          - "@jest/*"
          - "@types/jest"
          - "ts-jest"
          - "supertest"
          - "@types/supertest"
        update-types:
          - "minor"
          - "patch"
          - "major" # Jest major versions for coordinated testing updates

      # Build and development tools
      build-and-dev-tools:
        patterns:
          - "concurrently"
          - "nodemon"
          - "husky"
          - "lint-staged"
          - "conventional-changelog-cli"
        update-types:
          - "minor"
          - "patch"

      # Semantic release ecosystem
      semantic-release-tools:
        patterns:
          - "semantic-release"
          - "@semantic-release/*"
          - "@commitlint/*"
        update-types:
          - "minor"
          - "patch"
          - "major" # Semantic release changes can affect workflow

      # Node.js development ecosystem
      nodejs-dev-ecosystem:
        patterns:
          - "@types/node"
          - "ts-node*"
          - "pino-pretty"
        update-types:
          - "minor"
          - "patch"

      # Utility packages
      utilities:
        patterns:
          - "js-yaml"
          - "@types/js-yaml"
          - "license-checker"
        update-types:
          - "minor"
          - "patch"

    # Ignore specific packages that require manual review
    ignore:
      - dependency-name: "node" # Node.js version should be updated manually
      - dependency-name: "yarn" # Package manager version should be updated manually
      - dependency-name: "winston"
        update-types: ["version-update:semver-major"] # Major logging changes need review

  # Docker ecosystem - Base images and service containers
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 9 * * 1,3" # Monday and Wednesday at 09:00 UTC
      timezone: "UTC"
    labels:
      - "dependencies"
      - "dependabot"
      - "docker"
    reviewers:
      - "llevintza"
    assignees:
      - "llevintza"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "docker: "
      include: "scope"

    # Group Docker images by purpose
    groups:
      # Node.js base images
      node-images:
        patterns:
          - "node"
          - "node:*"
        update-types:
          - "minor"
          - "patch"

      # AWS and Amazon services
      aws-services:
        patterns:
          - "amazon/*"
          - "aws/*"
        update-types:
          - "minor"
          - "patch"
          - "major"

      # Development and admin tools
      dev-tools:
        patterns:
          - "aaronshaf/*"
        update-types:
          - "minor"
          - "patch"
          - "major"

    # Ignore major Node.js version updates (handle manually)
    ignore:
      - dependency-name: "node"
        update-types: ["version-update:semver-major"]

  # GitHub Actions ecosystem - Action dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 9 * * 1,3" # Monday and Wednesday at 09:00 UTC
      timezone: "UTC"
    labels:
      - "dependencies"
      - "dependabot"
      - "github-actions"
    reviewers:
      - "llevintza"
    assignees:
      - "llevintza"
    open-pull-requests-limit: 15
    commit-message:
      prefix: "ci: "
      include: "scope"

    # Group GitHub Actions by functionality
    groups:
      # Core GitHub Actions (checkout, setup, etc.)
      core-actions:
        patterns:
          - "actions/checkout"
          - "actions/setup-*"
          - "actions/upload-*"
          - "actions/download-*"
          - "actions/github-script"
        update-types:
          - "minor"
          - "patch"
          - "major"

      # Docker-related actions
      docker-actions:
        patterns:
          - "docker/*"
        update-types:
          - "minor"
          - "patch"
          - "major"

      # Security and analysis tools
      security-actions:
        patterns:
          - "aquasecurity/*"
          - "trufflesecurity/*"
        update-types:
          - "minor"
          - "patch"
          - "major"

      # Third-party utility actions
      utility-actions:
        patterns:
          - "amannn/*"
          - "peter-evans/*"
          - "softprops/*"
          - "dependabot/*"
        update-types:
          - "minor"
          - "patch"
          - "major"
