name: Dependabot Auto-merge

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  auto-merge:
    name: Auto-merge Dependabot PRs
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Get PR metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run quality checks
        id: quality
        continue-on-error: true
        run: |
          echo "Running quality checks..."
          
          # Type checking
          yarn type-check
          echo "type_check=passed" >> $GITHUB_OUTPUT
          
          # Linting
          yarn lint:check
          echo "lint_check=passed" >> $GITHUB_OUTPUT
          
          # Build test
          yarn build
          echo "build_check=passed" >> $GITHUB_OUTPUT
          
          echo "✅ All quality checks passed"

      - name: Run tests
        id: tests
        continue-on-error: true
        run: |
          echo "Running test suite..."
          yarn test
          echo "tests=passed" >> $GITHUB_OUTPUT
          echo "✅ Tests passed"

      - name: Determine if safe to auto-merge
        id: auto-merge-decision
        run: |
          # Check if this is a safe update to auto-merge
          UPDATE_TYPE="${{ steps.metadata.outputs.update-type }}"
          DEPENDENCY_TYPE="${{ steps.metadata.outputs.dependency-type }}"
          PACKAGE_ECOSYSTEM="${{ steps.metadata.outputs.package-ecosystem }}"
          
          echo "Update type: $UPDATE_TYPE"
          echo "Dependency type: $DEPENDENCY_TYPE"
          echo "Package ecosystem: $PACKAGE_ECOSYSTEM"
          
          # Conditions for auto-merge:
          # 1. Patch updates for any dependency
          # 2. Minor updates for development dependencies
          # 3. All quality checks passed
          # 4. Tests passed
          
          AUTO_MERGE=false
          
          if [[ "${{ steps.quality.outputs.type_check }}" == "passed" ]] && \
             [[ "${{ steps.quality.outputs.lint_check }}" == "passed" ]] && \
             [[ "${{ steps.quality.outputs.build_check }}" == "passed" ]] && \
             [[ "${{ steps.tests.outputs.tests }}" == "passed" ]]; then
            
            if [[ "$UPDATE_TYPE" == "version-update:semver-patch" ]]; then
              echo "✅ Auto-merge approved: Patch update with passing checks"
              AUTO_MERGE=true
            elif [[ "$UPDATE_TYPE" == "version-update:semver-minor" ]] && [[ "$DEPENDENCY_TYPE" == "indirect" ]]; then
              echo "✅ Auto-merge approved: Minor update for indirect dependency"
              AUTO_MERGE=true
            elif [[ "$DEPENDENCY_TYPE" == "direct:development" ]] && [[ "$UPDATE_TYPE" == "version-update:semver-minor" ]]; then
              echo "✅ Auto-merge approved: Minor update for dev dependency"
              AUTO_MERGE=true
            else
              echo "⚠️ Auto-merge not approved: $UPDATE_TYPE $DEPENDENCY_TYPE requires manual review"
            fi
          else
            echo "❌ Auto-merge not approved: Quality checks or tests failed"
          fi
          
          echo "auto_merge=$AUTO_MERGE" >> $GITHUB_OUTPUT

      - name: Auto-approve PR
        if: steps.auto-merge-decision.outputs.auto_merge == 'true'
        run: |
          gh pr review --approve "${{ github.event.pull_request.number }}" --body "✅ Auto-approved: Safe dependency update with passing checks"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge
        if: steps.auto-merge-decision.outputs.auto_merge == 'true'
        run: |
          gh pr merge --auto --squash "${{ github.event.pull_request.number }}"
          echo "✅ Auto-merge enabled for PR #${{ github.event.pull_request.number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add comment for manual review
        if: steps.auto-merge-decision.outputs.auto_merge == 'false'
        run: |
          gh pr comment "${{ github.event.pull_request.number }}" --body "🔍 **Manual Review Required**

          This dependency update requires manual review:
          - **Update Type**: ${{ steps.metadata.outputs.update-type }}
          - **Dependency Type**: ${{ steps.metadata.outputs.dependency-type }}
          - **Package**: ${{ steps.metadata.outputs.dependency-names }}
          
          **Quality Checks**:
          - Type Check: ${{ steps.quality.outputs.type_check || 'failed' }}
          - Lint Check: ${{ steps.quality.outputs.lint_check || 'failed' }}
          - Build Check: ${{ steps.quality.outputs.build_check || 'failed' }}
          - Tests: ${{ steps.tests.outputs.tests || 'failed' }}
          
          Please review the changes and merge manually if appropriate."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
